accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgot_password, name='forgot_password'),
    

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_passwordValidation/<uidb64>/<token>/', views.reset_passwordValidation, name='reset_passwordValidation'),
    path('resetPassword/', views.reset_password, name='reset_password'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),


]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),
    
    path('checkout/', views.checkout, name='checkout'),

]

gadgetzone/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(config('ADMIN_URL', cast=str), admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

# configuring media files url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have a unique email')
        
        if not username:
            raise ValueError('User must have a unique username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True

        user.save(using=self._db)
        return user



class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50, )
    last_name = models.CharField(max_length=50, )
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = PhoneNumberField(blank=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    # login fields
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    profile_picture = models.ImageField(upload_to='user_profile', blank=True)
    city = models.CharField(max_length=20, blank=True)
    state = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1}, {self.address_line_2}'

accounts/forms.py
from django import forms
from .models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name',  'phone_number', 'email', 'password']

    def __init__(self,*args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter E-mail address'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter your Phone Number'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Password does not match!")



class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name',  'phone_number']

    def __init__(self,*args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ['address_line_1', 'address_line_1',  'city', 'state', 'country', 'profile_picture']

    def __init__(self,*args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import accounts
from email.message import EmailMessage
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, UserForm, UserProfileForm
from . models import Account, UserProfile
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

# imports for email verificatio
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.http import HttpResponse

from carts.models import Cart, CartItem
from carts.views import _get_cart_id
from orders.models import Order, OrderItem
import requests


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            username = email.split('@')[0]

            user = Account.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email,  password=password)
            user.phone_number = phone_number
            user.save()
            
            # User Activation
            current_site = get_current_site(request)
            mail_subject = "Confirm the activation of your account."
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            return redirect('/accounts/login/?command=verification&email='+email)
    else:
        form = RegistrationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)


def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_get_cart_id(request))
                cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    
                    # getting the product variation by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = list(item.variation.all())
                        product_variation.append(variation)
                    
                    # get the cart items from the user to access his porduct variation
                    cart_item = CartItem.objects.filter(user=user)
                    existing_variation_list = []
                    cart_id_list = []
                    for item in cart_item:
                        existing_variation = list(item.variation.all())
                        existing_variation_list.append(existing_variation)
                        cart_id_list.append(item.id)

                    for product_variant in product_variation:
                        if product_variant in existing_variation_list:
                            variation_index = existing_variation_list.index(product_variant)
                            item_id = cart_id_list[variation_index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user 
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            
            auth.login(request, user)
            messages.success(request, "Logged in Successfully")
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboard')
        else:
            messages.error(request, "Invalid login Credentials")
            return redirect('accounts:login')

    return render(request, 'accounts/login.html')

@login_required(login_url='accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, "Logged out Successfully")
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is verified and activated.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Invalid activation link")
        return redirect('accounts:register')


@login_required(login_url='accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()

    user_profile = UserProfile.objects.get(user_id=request.user.id)
    context = {
        'orders_count': orders_count,
        'user_profile': user_profile,
    }
    return render(request, 'accounts/dashboard.html', context)
    

def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # reset password email
            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, "Reset password email sent successfully!")
            return redirect('accounts:login')
        else:
            messages.error(request, "Account does not exist")
            return redirect('accounts:forgot_password')

    return render(request, 'accounts/forgot_password.html')


def reset_passwordValidation(request, uidb64, token ):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, "Setup the new password for your account.")
        return redirect('accounts:reset_password')
    else:
        messages.error(request, "Invalid/Expired link")
        return redirect('accounts:forgot_password')


def reset_password(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        
        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset Successful!')
            return redirect('accounts:login')
        else:
            messages.error(request, "Passwords doesn't match")
            return redirect('accounts:reset_password')

    else:
        return render(request, 'accounts/reset_password.html')


@login_required(login_url='accounts:login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders': orders
    }
    return render(request, 'accounts/my_orders.html', context)

@login_required(login_url='accounts:login')
def edit_profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            messages.success(request, "Your Profile has been updated successfully")
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        user_profile_form = UserProfileForm(instance=user_profile)
    
    context = {
        'user_form': user_form,
        'user_profile_form': user_profile_form,
        'user_profile': user_profile,
    }

templates/accounts/account_verification_email.html
{% autoescape off %}
    {% csrf_token %}
    Hi {{ user.first_name }},
    
    We're excited to have you. 

    Please click on the link below to verify your registration :-
    http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

    Discard if it's not you or already verified.

    Regards
    Team GadgetZone 
{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% block title %}
    <title>Change Password</title>
{% endblock title %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	<aside class="col-md-3">
	{% include 'includes/dashboard_sidebar.html' %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change Your Password</strong>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class=col-md-12>
                    <form action="{% url 'accounts:change_password' %}" method="POST">
                    {% csrf_token %}
                        <div class="form-group">
                            <label>Current Password</label>
                            <input class="form-control" type="password" name="current_password" placeholder="Current Password" required>
                        </div>
                        <div class="form-group">
                            <label>Enter New Password</label>
                            <input class="form-control" type="password" name="new_password" placeholder="New Password" required>
                        </div>
                        <div class="form-group">
                            <label>Confirm New Password</label>
                            <input class="form-control" type="password" name="confirm_new_password" placeholder="Confirm New Password" required>
                        </div>

                        <input type="submit" class="btn btn-primary" value="submit">
                    </form>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block title %}
    <title>Dashboard</title>
{% endblock title %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	<aside class="col-md-3">
	{% include 'includes/dashboard_sidebar.html' %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{ user.full_name }}</span>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class=col-md-6>
					<div class="card" style="text-align:center;">
						<div class="card-body">
							<h5 class="card-title">Total Orders</h5>
							<h4>{{ orders_count }}</h4>
							<a href="{% url 'accounts:my_orders' %}">View Orders</a>
						</div>
					</div>
				</div>
				<div class=col-md-6>
					<div class="card" style="text-align:center;">
						<div class="card-body">
							<img src="{{ user_profile.profile_picture.url }}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
							<p class="mb-0">{{ user.email }}</p>
							<p>{{ user.phone_number }}</p>
						</div>
					</div>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block title %}
    <title>Edit Profile</title>
{% endblock title %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	<aside class="col-md-3">
	{% include 'includes/dashboard_sidebar.html' %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit Your Profile</strong>
		</header>
		<div class="card-body">
            <div class="text-right">
                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture" width="100" style="border-radius:50%;">
            </div>
            <br>
			<div class="row"> 
				<div class=col-md-12>
                    <form action="{% url 'accounts:edit_profile' %}" method="POST"    enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>First Name</label>
                                {{ user_form.first_name }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Last Name</label>
                                {{ user_form.last_name }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Phone Number</label>
                                {{ user_form.phone_number }}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Profile Picture</label>
                                {{ user_profile_form.profile_picture }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Address Line 1</label>
                            {{ user_profile_form.address_line_1 }}
                        </div>
                        <div class="form-group">
                            <label>Address Line 2</label>
                            {{ user_profile_form.address_line_2 }}
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>City</label>
                                {{ user_profile_form.city }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>State</label>
                                {{ user_profile_form.state }}
                            </div>
                            <div class="form-group col-md-4">
                                <label>Country</label>
                                {{ user_profile_form.country }}
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" value="save">
                    </form>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}
{% block title %}
    <title>Forgot Password</title>
{% endblock title %}

{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
          {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:forgot_password' %}" method="POST">
      {% csrf_token %}


          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email" >
          </div> <!-- form-group// -->
          
          <div class="form-group">
            <p class="text-right mt-4">Got Password? <a href="{% url 'accounts:login' %}">Login</a></p>
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>


<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
    <title>Sign In</title>
{% endblock title %}

{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
{% if request.GET.command == 'verification' %}
{% csrf_token %}
    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
        Thanks for registering with us. We have sent you a verification mail to your Email 
        ({{ request.GET.email }}). Verify it to enjoy flawless service.
        <br><br>
        Already verified? <a href="{% url 'accounts:login' %}">Login</a>
    </div>

{% else %}
    
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
          {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}


          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email" >
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name='password'>
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="#" class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>

{% endif %}
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% block title %}
    <title>My Orders</title>
{% endblock title %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	<aside class="col-md-3">
	{% include 'includes/dashboard_sidebar.html' %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Your Order History:</strong>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class=col-md-12>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Order #</th>
                                <th scope="col">Billing Name</th>
                                <th scope="col">Phone</th>
                                <th scope="col">Order Total</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <th scope="row"><a href="{% url 'accounts:order_detail' order.order_number %}">{{ order.order_number }}</a></th>
                                <td>{{ order.full_name }}</td>
                                <td>{{ order.phone_number }}</td>
                                <td>${{ order.order_total }}</td>
                                <td>{{ order.created_at }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/accounts/reset_password_email.html
{% autoescape off %}
    {% csrf_token %}
    Hi {{ user.first_name }},

    As requested, Please click on the link below to reset your  account's password:-
    http://{{domain}}{% url 'accounts:reset_passwordValidation' uidb64=uid token=token %}

    Discard if it's not you or already have a password.

    Regards
    Team GadgetZone 
{% endautoescape %}