accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgot_password, name='forgot_password'),
    

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_passwordValidation/<uidb64>/<token>/', views.reset_passwordValidation, name='reset_passwordValidation'),
    path('resetPassword/', views.reset_password, name='reset_password'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),


]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),
    
    path('checkout/', views.checkout, name='checkout'),

]

gadgetzone/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(config('ADMIN_URL', cast=str), admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

# configuring media files url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.order_complete, name='order_complete'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details,
    name='product_details'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review')

]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price *self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from audioop import avg
from django.db import models
from django.urls import reverse
from category.models import Category
from accounts.models import Account
from django.db.models import Avg, Count

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='images/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    

    def get_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])

    def averageReviews(self):
        reviews = ReviewAndRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReviews(self):
        reviews = ReviewAndRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count




    def __str__(self):
        return self.product_name



class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'Product Gallery'
        verbose_name_plural = 'Product Gallery'


class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(is_active=True)
    
    def color(self):
        return self.all().filter(variation_category='color')
    
    def size(self):
        return self.all().filter(variation_category='size')

    def style_name(self):
        return self.all().filter(variation_category='style name')

    def pattern_name(self):
        return self.all().filter(variation_category='pattern name')



variants_choices = (
    ('color', 'color'),
    ('size', 'size'),
    ('style name', 'style name'),
    ('pattern name', 'pattern name'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=255, choices=variants_choices)
    variation_value = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


    
class ReviewAndRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms
from .models import ReviewAndRating


class ReviewAndRatingForm(forms.ModelForm):
    class Meta:
        model = ReviewAndRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Cart, CartItem
from store.models import Product, Variation
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

# Create your views here.

# method to get cart id based on session key
def _get_cart_id(request):
    cart_id = request.session.session_key
    if not cart_id:
        cart_id = request.session.create()
    return cart_id

def add_to_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    
    # if the user is authenticated
    if current_user.is_authenticated:
        product_variation = []

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if  cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            
            existing_variation_list = []
            cart_id_list = []
            for item in cart_item:
                existing_variation = list(item.variation.all())
                existing_variation_list.append(existing_variation)
                cart_id_list.append(item.id)

            if product_variation in existing_variation_list:
                variation_index = existing_variation_list.index(product_variation)
                item_id = cart_id_list[variation_index]
                item = CartItem.objects.get(product=product,  id=item_id)
                item.quantity += 1
                item.save()
            else:
                cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    cart_item.variation.clear()           
                    cart_item.variation.add(*product_variation)
                
                cart_item.save()
        else:
            cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)

            cart_item.save()

        return redirect('carts:cart')

    # if the user is not authenticated
    else:   
        product_variation = []

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            # get cart using the cart id present in the session
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id = _get_cart_id(request))

        cart.save()

        cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

        if  cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            
            existing_variation_list = []
            cart_id_list = []
            for item in cart_item:
                existing_variation = list(item.variation.all())
                existing_variation_list.append(existing_variation)
                cart_id_list.append(item.id)

            if product_variation in existing_variation_list:
                variation_index = existing_variation_list.index(product_variation)
                item_id = cart_id_list[variation_index]
                item = CartItem.objects.get(product=product, cart=cart, id=item_id)
                item.quantity += 1
                item.save()
            else:
                cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    cart_item.variation.clear()           
                    cart_item.variation.add(*product_variation)
                
                cart_item.save()
        else:
            cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)

            cart_item.save()

        return redirect('carts:cart')


def  remove_from_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id = _get_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    
    except:
        pass

    return redirect('carts:cart')


def delete_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id = _get_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

    cart_item.delete()
    return redirect('carts:cart')

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (5 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total' : grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='accounts:login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (5 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total' : grand_total,
    }
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

<!-- ========================= TITLE========================= -->
{% block title %}
    <title>My Cart</title>
{% endblock title %}
<!-- ========================= TITLE-END//========================= -->

<!-- ========================= CONTENT========================= -->
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
    <h2 class="text-center"> Your Shopping Cart is Empty! </h2>
    <br>
    <div class="text-center">
        <a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>


<!---MESSAGE-->

{% else %}

<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
					{% if cart_item.variation.all %}
						{% for item in cart_item.variation.all %}
							{{ item.variation_category | capfirst}} : {{ item.variation_value | capfirst}} <br>
						{% endfor %}
					{% endif %}
						
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'carts:remove_from_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
							<div class="input-group-append">
								<form action="{% url 'carts:add_to_cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.variation.all %}
									<input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst}}" />
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i> </button>
								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{ cart_item.sub_total }}</var> 
			<small class="text-muted"> ${{ cart_item.product.price }} each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'carts:delete_cart_item' cart_item.product.id  cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')"class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Cart Price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->

{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>


{% endblock content %}
<!-- ========================= CONTENT END//========================= -->

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}

<!-- ========================= TITLE========================= -->
{% block title %}
    <title>Product Details</title>
{% endblock title %}
<!-- ========================= TITLE-END//===================== -->


<!-- ========================= SECTION CONTENT ========================= -->
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap"> 
	<div class="img-big-wrap mainImage">
	   <img src="{{ single_product.images.url }}">
	</div> <!-- img-big-wrap.// -->
	
</article> <!-- gallery-wrap .end// -->

<ul class="thumb">
	<li>
	<a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
	{% for i in product_gallery %}
		<a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
	{% endfor %}
	</li>
</ul>

		</aside>
		<main class="col-md-6 border-left">

<form action="{% url 'carts:add_to_cart' single_product.id %}" method="POST">
{% csrf_token %}
	<article class="content-body">

	<h2 class="title">{{ single_product.product_name }}</h2>
	<div class="rating-star">
		<span>
			<i class="fa fa-star{% if single_product.averageReviews < 0.5 %}-o{% elif single_product.averageReviews >= 0.5 and single_product.averageReviews < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averageReviews < 1.5 %}-o{% elif single_product.averageReviews >= 1.5 and single_product.averageReviews < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averageReviews < 2.5 %}-o{% elif single_product.averageReviews >= 2.5 and single_product.averageReviews < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averageReviews < 3.5 %}-o{% elif single_product.averageReviews >= 3.5 and single_product.averageReviews < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.averageReviews < 4.5 %}-o{% elif single_product.averageReviews >= 4.5 and single_product.averageReviews < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
			<span>{{ single_product.countReviews }} reviews</span>
		</span>
	</div>

	<div class="mb-3"> 
		<var class="price h4">$ {{ single_product.price }}</var> 
	</div> 

	<p>{{ single_product.description }}</p>


	<hr>
		{% if single_product.variation_set.color %}
			<div class="row">
				<div class="item-option-select">
					<h6>Choose Color</h6>
						<select name="color"  class="form-control" required>
							<option value="" disabled selected>--Select--</option>
						{% for option in single_product.variation_set.color %}
							<option value="{{ option.variation_value | lower }}">{{ option.variation_value | capfirst }}</option>
						{% endfor %}
						</select>
				</div>
			</div> <!-- row.// -->
		{% endif %}

		{% if single_product.variation_set.size %}
			<div class="row">
				<div class="item-option-select">
					<h6>Size</h6>
						<select name="size" class="form-control" required>
							<option value="" disabled selected>--Select--</option>
						{% for option in single_product.variation_set.size %}
							<option value="{{ option.variation_value | lower }}">{{ option.variation_value | capfirst }}</option>
						{% endfor %}
						</select>
				</div>
			</div> <!-- row.// -->
		{% endif %}


		{% if single_product.variation_set.style_name %}
			<div class="row">
				<div class="item-option-select">
					<h6>Style Name</h6>
						<select name="style name" class="form-control" required>
							<option value="" disabled selected>--Select--</option>
						{% for option in single_product.variation_set.style_name %}
							<option value="{{ option.variation_value | lower }}">{{ option.variation_value | capfirst }}</option>
						{% endfor %}
						</select>
				</div>
			</div> <!-- row.// -->
		{% endif %}

		{% if single_product.variation_set.pattern_name %}
			<div class="row">
				<div class="item-option-select">
					<h6>Pattern Name</h6>
						<select name="pattern name" class="form-control" required>
							<option value="" disabled selected>--Select--</option>
						{% for option in single_product.variation_set.pattern_name %}
							<option value="{{ option.variation_value | lower }}">{{ option.variation_value | capfirst }}</option>
						{% endfor %}
						</select>
				</div>
			</div> <!-- row.// -->
		{% endif %}
	<hr>
		
		{% if single_product.stock <= 0 %}
			<h5 class="text-danger">Out Of Stock</h5>
		{% else %}
			<button type="submit" class="btn  btn-primary">  <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i>  </button>
		{% endif %}
	</article> <!-- product-info-aside .// -->
</form>

		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	

	<form action="{% url 'store:submit_review' single_product.id %}" method="POST">
	{% csrf_token %}
		<h5 class="">Write Your Review</h5>
		<div class="">
			<!--Rating Stars-->
			<label for="">How do you rate this product?</label>	
			<br>
			<div class="rate">
				<input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
				<input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
				<input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
				<input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
				<input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
				<input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5"  class="half"></label>
				<input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
				<input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5"  class="half"></label>
				<input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
				<input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
			</div>
			<br>

			Review Title: 
			<input type="text" class="form-control" name="subject">
			<br>
			Review:
			<textarea name="review" rows="5" class="form-control"></textarea>
			<br>
			
			{% if user.is_authenticated %}
				{% if order_item %}
					<input type="submit" value="Submit Review" class="btn btn-primary">	
				{% else %}
					<p>You must purchase this product in order to post a review.</p>
				{% endif %}
			{% else %}
				<p>You must be logged in to post a review. <span class=""><a href="{% url 'accounts:login' %}">Login now</a></span></p>
			{% endif %}
				
		</div>
		<br>
		{% include 'includes/alerts.html' %}

	</form>
	<br> 

	<header class="section-heading">
		<h3>Customer Reviews </h3>
		<div class="rating-star">
			<span>
				<i class="fa fa-star{% if single_product.averageReviews < 0.5 %}-o{% elif single_product.averageReviews >= 0.5 and single_product.averageReviews < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.averageReviews < 1.5 %}-o{% elif single_product.averageReviews >= 1.5 and single_product.averageReviews < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.averageReviews < 2.5 %}-o{% elif single_product.averageReviews >= 2.5 and single_product.averageReviews < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.averageReviews < 3.5 %}-o{% elif single_product.averageReviews >= 3.5 and single_product.averageReviews < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.averageReviews < 4.5 %}-o{% elif single_product.averageReviews >= 4.5 and single_product.averageReviews < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
				<span>{{ single_product.countReviews }} reviews</span>
			</span>
		</div>
		
	</header>

{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="{% static "./images/avatars/default_profile_image.png" %}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.updated_at }} </span>  
				<h6 class="mb-1">{{ review.user.full_name }} </h6>
				<div class="rating-star">
					<span>
						<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
					</span>
				</div>
				
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<h6>{{ review.subject }}</h6>
			<p>{{ review.review }}</p>	
		</div>
	</article>
{% endfor %}

	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>

{% endblock content %}
<!-- ========================= SECTION CONTENT END// ========================= -->